### ISSUE TITLE
Stuck at "RLS analysis: starting up"

### ISSUE THREAD

**Issue by agentsim** [rust-lang/rls-vscode#130] opened 2017-08-22 19:37 UTC
Since the 0.2.2 update, RLS never gets beyond this stage. I get the following error output:
```
[Error - 3:35:48 PM] Request textDocument/codeAction failed.
  Message: Invalid request
  Code: -32600 
```

**Comment by nrc** [comment] 2017-08-22 19:52
Could you point me at the project you're testing with please? And whether you have any settings set in VSCode? If you like, you could try some of the ideas in https://github.com/rust-lang-nursery/rls/blob/master/debugging.md (especially around logging) to see if you can get more info.

**Comment by agentsim** [comment] 2017-08-22 19:58
Unfortunately it is a private project, so I cannot share the source code.

After restarting VSCode a few times and always being stuck in "starting up", I just started typing into a Rust source file and it immediately began analysis and then finished. It would appear it isn't stuck so much as it no longer automatically starts the analysis when I switch to the first Rust source tab.

**Comment by Xanewok** [comment] 2017-08-22 20:02
@nrc if I recall correctly, this is due to always passing `omitInitBuild: true`. Often I also don't have analysis started when I just open the project and let it sit there, I need to start typing to request the analysis. This isn't 100% the case, so I can look into that and see if sometimes we don't build on the config change message or something else that sometimes doesn't start the analysis immediately without user's input.

**Comment by nrc** [comment] 2017-08-22 20:09
Hmm, I've intermittently observed this behaviour since we first started the extension, but I've never been able to reliably reproduce. My theory is that it is a VSCode bug and the extension is not being started, but if the behaviour changed with a new version of the extension, that suggests that it might be an issue there. (I don't think it is because of `omitInitBuild` - that was in the previous version and I've observed this behaviour before we added it).

**Comment by coder543** [comment] 2017-08-23 00:57
I finally decided to try this plugin out tonight, and I immediately hit this same issue, and I can repeatedly reproduce it by closing and re-opening VS Code. The solution is as @Xanewok said: you have to start typing _anywhere_ in a Rust file to give the plugin the "kick" that's needed to get it started on analysis.

Once the analysis begins, this plugin causes VS Code to jump from using about 8% of my laptop's CPU to about 40%, even when the plugin seems to be doing no useful work. I'm tempted to say this is caused by the constantly circling "RLS analysis: working" + a spinning icon thing, even though it's not doing anything useful. Completions and other things finished long ago, and my cursor is simply sitting on an empty line, doing nothing.

**Comment by Xanewok** [comment] 2017-08-23 08:44
@coder543 Despite VS Code having some fiascos, like that blinking cursor causing 20% of the CPU, I'm pretty sure the indicator itself consumes almost no amount of CPU power - it's a simple node js timer replacing a text in a box.

Could you take a look at the processes being run, either via `htop` or any other process manager in your OS? When the build is started, RLS runs a check routine on every dirty crate target and needs to process resulting analysis data at the end - this may be quite CPU-heavy. You also have to give it some time when running the RLS on a project for the first time - it needs to build the index for the whole project, including almost all dependencies, so this can take some time at first. Then, subsequent builds should last fairly short.

**Comment by coder543** [comment] 2017-08-23 12:09
Prior to posting that comment, I did exactly that. I use VS Code as my primary editor, and I've been happily using the `kalitaalexey` plugin. VS Code was the only process consuming CPU according to `htop` after the initial analysis, and it was just sitting there saying the analysis was "working" when I could not find any process doing work besides the VS Code process.

With the `rls-vscode` plugin installed, prior to _typing_ in a Rust file, normal CPU usage. As soon as any typing occurred, the CPU usage never seemed to recover without restarting VS Code.

I can try to do more testing soon, but I only had about 10 to 15 minutes to play around with this plugin before I had to uninstall it and reinstall the other Rust plugin so I could get some work done.

**Comment by Xanewok** [comment] 2019-04-07 11:46
Do you still experience this?

**Comment by agentsim** [comment] 2019-04-08 00:00
> Do you still experience this?

I do not.

**Comment by Xanewok** [comment] 2019-04-08 06:37
I’ll close the issue then but please reopen if that’s still the case!

**Closed by Xanewok** 2019-04-08 06:37 UTC
