### ISSUE TITLE
No intelligent complementing for extern crate

### ISSUE THREAD

**Issue by caibirdme** [rust-lang/rls-vscode#427] opened 2018-09-14 00:53 UTC
Hi, I'm new here and follow the rust guide do some practice. I found the intelligent complementing doesn't work for extern crate, but for std it works. Am I missing something?
```rust
extern crate rand;

use rand::Rng;  // no intelliSense, I don't know how many choices I have besides Rng

fn main() {
  let secret_num = rand::thread_rng().gen_range(1,101); // no intelliSense either, I don't know the method rand package provide and don't know where to find them.
  let mut number = String::new();
  io::stdin().read_line(&mut number).expect("some...");  // it works here
}
```

**Comment by kuxv** [comment] 2018-09-28 15:12
Duplicate of #386 ?

**Comment by Elementals** [comment] 2018-10-08 13:48
Workaround: **restarting rls** (update rls just doesn't help).

**Comment by Xanewok** [comment] 2019-04-07 18:49
Related LF/CRLF fix in the Racer has been merged for quite some time now and I believe this should be available in the stable release, closing the issue.

**Closed by Xanewok** 2019-04-07 18:49 UTC
