### ISSUE TITLE
extension does not work with VSCode 1.18.0

### ISSUE THREAD

**Issue by Geobert** [rust-lang/rls-vscode#188] opened 2017-11-10 14:26 UTC
updated VSCode to 1.18.0 and Rust (rls) to 0.3.2 and apart of syntax highlight, nothing seems to work:
go to definition
find references

etc.

tested on Win 10 64bits

**Comment by senden9** [comment] 2017-11-10 15:29
Same effect as in  #186? So a spinning "RLS: working"? If yes this is maybe a duplicate.

**Comment by Geobert** [comment] 2017-11-10 16:11
Nope, RLS: done here

**Comment by AnyCPU** [comment] 2017-11-10 17:35
the same https://github.com/rust-lang-nursery/rls-vscode/issues/185

**Comment by forbjok** [comment] 2017-11-10 21:12
Having the same issue.

In the "Rust Language" output pane, it shows the following error:
```
thread '<unnamed>' panicked at 'need to specify SYSROOT or RUSTC env vars, or rustc must be in PATH', src\libcore\option.rs:839:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

which seems to indicate that it can't find "rustc", but it is definitely in my PATH.

**Comment by nrc** [comment] 2017-11-10 21:21
There's a fix on master which should address this. Currently waiting for it to get processed through the Rust infra and hit rustup. Fingers crossed that fixes things here.

**Comment by wangii** [comment] 2017-11-11 20:51
fixed in today's nightly build. let's hope it'll not happen again.

**Comment by Geobert** [comment] 2017-11-11 23:07
Is that supposed to fix VS Code Rust (rls) plugin?

**Comment by Yanpas** [comment] 2017-11-12 10:36
Hover, real-time errors and refactoring do not work anymore

**Comment by paukul** [comment] 2017-11-27 11:45
same here, hover, errors etc. not working anymore. Is the cause for this known? Anything one can do to help?

**Comment by Yanpas** [comment] 2017-11-27 11:47
@paukul They started to work after:
1. I ran rustup update and updated everything I could
2. Switched rls to stable in vs code settings
3. Added misssing dll's to PATH for my project

**Comment by paukul** [comment] 2017-11-27 12:06
FYI: after enabling logging, I noticed the following errors piling up in the rls<number>.logs:
```
thread 'rustc' panicked at 'Could not deserialize save-analysis config: MissingFieldError("reachable_only")', src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: internal compiler error: unexpected panic
```

@Yanpas how did you switch to stable rls?

**Comment by paukul** [comment] 2017-11-27 12:09
this error seems to be known: https://github.com/rust-lang/rust/issues/46244

**Comment by paukul** [comment] 2017-11-27 12:34
@Yanpas cheers, switching it to stable for now fixed the issue and made it work again, thanks.
For everyone who's curious:

```
 "rust-client.channel": "stable"
```
in the (workspace) settings

**Comment by oleid** [comment] 2017-11-28 21:45
It doesn't work for me - neither with `stable`, nor with `nightly-2017-11-15-x86_64-unknown-linux-gnu`. rls, however, works with the later. I get some output like:
<pre>
{"message":"unused import: `c_int`","code":{"code":"unused_imports","explanation":null},"level":"warning","spans":[{"file_name":"sync/prog/gpgpu/stochastic_particles/compute_kernel/lib.rs","byte_start":53,"byte_end":58,"line_start":4,"line_end":4,"column_start":12,"column_end":17,"is_primary":true,"text":[{"text":"use libc::{c_int};","highlight_start":12,"highlight_end":17}],"label":null,"suggested_replacement":null,"expansion":null}],"children":[{"message":"#[warn(unused_imports)] on by default","code":null,"level":"note","spans":[],"children":[],"rendered":null}],"rendered":null}
{"message":"unused import: `ndarray::prelude::*;`","code":{"code":"unused_imports","explanation":null},"level":"warning","spans":[{"file_name":"sync/prog/gpgpu/stochastic_particles/compute_kernel/lib.rs","byte_start":65,"byte_end":85,"line_start":5,"line_end":5,"column_start":5,"column_end":25,"is_primary":true,"text":[{"text":"use ndarray::prelude::*;","highlight_start":5,"highlight_end":25}],"label":null,"suggested_replacement":null,"expansion":null}],"children":[{"message":"#[warn(unused_imports)] on by default","code":null,"level":"note","spans":[],"children":[],"rendered":null}],"rendered":null}
{"message":"missing field `positions` in initializer of `root::SimulationState`","code":{"code":"E0063","explanation":"\nThis error indicates that during an attempt to build a struct or struct-like\nenum variant, one of the fields was not provided. Erroneous code example:\n\n```compile_fail,E0063\nstruct Foo {\n    x: i32,\n    y: i32,\n}\n\nfn main() {\n    let x = Foo { x: 0 }; // error: missing field: `y`\n}\n```\n\nEach field should be specified exactly once. Example:\n\n```\nstruct Foo {\n    x: i32,\n    y: i32,\n}\n\nfn main() {\n    let x = Foo { x: 0, y: 0 }; // ok!\n}\n```\n"},"level":"error","spans":[{"file_name":"sync/prog/gpgpu/stochastic_particles/compute_kernel/lib.rs","byte_start":745,"byte_end":766,"line_start":36,"line_end":36,"column_start":21,"column_end":42,"is_primary":true,"text":[{"text":"    let mut state = root::SimulationState {","highlight_start":21,"highlight_end":42}],"label":"missing `positions`","suggested_replacement":null,"expansion":null}],"children":[],"rendered":null}
{"message":"mismatched types","code":{"code":"E0308","explanation":"\nThis error occurs when the compiler was unable to infer the concrete type of a\nvariable. It can occur for several cases, the most common of which is a\nmismatch in the expected type that the compiler inferred for a variable's\ninitializing expression, and the actual type explicitly assigned to the\nvariable.\n\nFor example:\n\n```compile_fail,E0308\nlet x: i32 = \"I am not a number!\";\n//     ~~~   ~~~~~~~~~~~~~~~~~~~~\n//      |             |\n//      |    initializing expression;\n//      |    compiler infers type `&str`\n//      |\n//    type `i32` assigned to variable `x`\n```\n"},"level":"error","spans":[{"file_name":"sync/prog/gpgpu/stochastic_particles/compute_kernel/lib.rs","byte_start":811,"byte_end":819,"line_start":39,"line_end":39,"column_start":23,"column_end":31,"is_primary":true,"text":[{"text":"        root::RunDemo(settings, state) == 0","highlight_start":23,"highlight_end":31}],"label":"expected *-ptr, found struct `root::SimulationSettingsBase`","suggested_replacement":null,"expansion":null}],"children":[{"message":"expected type `*const root::SimulationSettingsBase<root::float3_simple>`\n   found type `root::SimulationSettingsBase<root::float3_simple>`","code":null,"level":"note","spans":[],"children":[],"rendered":null}],"rendered":null}
{"message":"mismatched types","code":{"code":"E0308","explanation":"\nThis error occurs when the compiler was unable to infer the concrete type of a\nvariable. It can occur for several cases, the most common of which is a\nmismatch in the expected type that the compiler inferred for a variable's\ninitializing expression, and the actual type explicitly assigned to the\nvariable.\n\nFor example:\n\n```compile_fail,E0308\nlet x: i32 = \"I am not a number!\";\n//     ~~~   ~~~~~~~~~~~~~~~~~~~~\n//      |             |\n//      |    initializing expression;\n//      |    compiler infers type `&str`\n//      |\n//    type `i32` assigned to variable `x`\n```\n"},"level":"error","spans":[{"file_name":"sync/prog/gpgpu/stochastic_particles/compute_kernel/lib.rs","byte_start":821,"byte_end":826,"line_start":39,"line_end":39,"column_start":33,"column_end":38,"is_primary":true,"text":[{"text":"        root::RunDemo(settings, state) == 0","highlight_start":33,"highlight_end":38}],"label":"expected *-ptr, found struct `root::SimulationState`","suggested_replacement":null,"expansion":null}],"children":[{"message":"expected type `*mut root::SimulationState`\n   found type `root::SimulationState`","code":null,"level":"note","spans":[],"children":[],"rendered":null}],"rendered":null}
{"message":"aborting due to 3 previous errors","code":null,"level":"error","spans":[],"children":[],"rendered":null}
</pre>
There is no output in the debugger console. This is my config:
<pre>
{
    "rust.workspace_mode": true,
    "rust-client.logToFile": true,
    "rust.unstable_features": true,
    "rust-client.channel": "nightly-2017-11-15-x86_64-unknown-linux-gnu"
}
</pre>

**Comment by leshow** [comment] 2017-11-29 02:41
I'm having this issue on the nightly compiler also, same error

```
thread 'rustc' panicked at 'Could not deserialize save-analysis config: MissingFieldError("reachable_only")', src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: internal compiler error: unexpected panic
```

**Comment by oleid** [comment] 2017-11-29 19:59
@leshow : That's a bug in nightly rls, not the extension. Try an earlier version, i.e. by setting `    "rust-client.channel": "nightly-2017-11-15-x86_64-unknown-linux-gnu"`

**Comment by paukul** [comment] 2017-12-01 10:29
works again in todays nightly

**Comment by fuszenecker** [comment] 2018-03-06 19:13
Doesn't work with 

nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.26.0-nightly (c9334404f 2018-03-05)

**Comment by Frederick888** [comment] 2018-03-07 05:05
Is this again a bug in `rls`?

Perhaps a bit off-topic but since rustup has implemented "update only if installed components are all available", is it better to have some tests to prevent buggy `rls`s from being published?

**Comment by alexreg** [comment] 2018-03-07 16:29
Okay, interestingly enough, everything seems to be working on stable and nightly now, since my last `rustup update`! Odd.

**Comment by Geobert** [comment] 2018-03-07 16:34
You are lucky, it's not working for me. `nightly-x86_64-pc-windows-msvc unchanged - rustc 1.26.0-nightly (2789b067d 2018-03-06)` or even stable

**Comment by nrc** [comment] 2018-03-08 02:06
@Geobert @fuszenecker could you give some more details please?

> is it better to have some tests to prevent buggy rls's from being published?

We do test every RLS we publish and publish working versions, furthermore we no longer publish nightly Rust without a working RLS. However, some problems aren't caught by our tests because they only occur on certain projects or platforms.

**Comment by Geobert** [comment] 2018-03-08 08:16
On [cobalt.rs](https://github.com/cobalt-org/cobalt.rs), with `nightly-x86_64-pc-windows-msvc unchanged - rustc 1.26.0-nightly (2789b067d 2018-03-06)`. No find definition, nor find references. Completion seems to work though.

**Comment by Geobert** [comment] 2018-03-08 18:25
This project doesn't work neither (since end of Jan) https://github.com/Geobert/rusty_flexi

**Comment by Xanewok** [comment] 2019-04-07 21:06
Right now the issue seems too vague - the extension has been working correctly for quite some time now. If you experience any problems, please make sure to file another issue with reproduction steps. Thanks!

**Closed by Xanewok** 2019-04-07 21:06 UTC
Labels: bug
