### ISSUE TITLE
Cannot goto define for std library

### ISSUE THREAD

**Issue by davidwudv** [rust-lang/rls-vscode#336] opened 2018-06-12 07:05 UTC
![image](https://user-images.githubusercontent.com/4150570/41274995-04cc8ab8-6e52-11e8-809e-c49c258a0ba1.png)

vscode info:

> Version 1.24.0
> Commit 6a6e02cef0f2122ee1469765b704faf5d0e0d859
> Date 2018-06-06T17:35:40.560Z
> Shell 1.7.12
> Renderer 58.0.3029.110
> Node 7.9.0
> Architecture x64

extension version: 0.4.5

**Comment by jonathan-s** [comment] 2018-06-18 18:00
Having this issue as well.

**Comment by jonathan-s** [comment] 2018-06-18 18:03
Actually, if you use the setting `"rust-client.channel": "nightly"` you'll be able to go to the definition.

**Comment by jonathan-s** [comment] 2018-06-19 18:43
For me it works multiple times, not sure whether it'll make a difference but have you tried updating rust to the latest version?

**Comment by davidwudv** [comment] 2018-06-20 01:35
I have updated rust and all component to the latest.
But it's still not working.  :(

**Comment by nrc** [comment] 2018-06-20 23:38
Jumping into std (or any library) should work (you might need to use master, rather than the current release). Once we're in std (or whatever) the RLS has the info, but I think there is a bug in VSCode that means the RLS doesn't get called. I filed https://github.com/Microsoft/vscode-languageserver-node/issues/363, we'll see if such a thing exists or if it can be added...

**Comment by davidwudv** [comment] 2018-06-25 10:04
@nrc thank you

**Comment by nrc** [comment] 2018-07-12 02:37
Note to self: there's a suggestion for fixing this at https://github.com/Microsoft/vscode-languageserver-node/issues/363#issuecomment-403038160

**Comment by aloucks** [comment] 2018-07-12 02:44
While trying to debug why tooltips don't show the line separators I think I stumbled across the fix for this. 

```diff
--- a/src/extension.ts
+++ b/src/extension.ts
@@ -164,8 +164,8 @@ class ClientWorkspace {
         const clientOptions: LanguageClientOptions = {
             // Register the server for Rust files
             documentSelector: [
-                { language: 'rust', scheme: 'file', pattern: `${this.folder.uri.fsPath}/**/*` },
-                { language: 'rust', scheme: 'untitled', pattern: `${this.folder.uri.fsPath}/**/*` }
+                { language: 'rust', scheme: 'file' },
+                { language: 'rust', scheme: 'untitled' }
             ],
```

**Comment by aloucks** [comment] 2018-07-12 02:51
#366

**Comment by Xanewok** [comment] 2019-04-07 18:35
@davidwudv do you still encounter this? I can't reproduce this issue.

**Comment by davidwudv** [comment] 2019-04-08 04:01
@Xanewok  no, it's working now.

**Closed** 2019-04-12 06:59 UTC
Labels: bug
