### ISSUE TITLE
intellisense doesnt work for member functions or properties of types defined in crates.

### ISSUE THREAD

**Issue by haggerty-william** [rust-lang/rls-vscode#386] opened 2018-07-27 13:09 UTC
So I am a beginner with rust and I am trying to follow the pong tutorial for the amethyst game engine using vscode as my ide. At first I thought that there was no working intellisense at all but after a while I realized that it just didnt work on anything from any of the crates i use as a dependency. 
For example if I do:
use amethyst::renderer::DisplayConfig;
let path = "./resources/display_config.ron";
let input_bundle = InputBundle::<String, String>::new().with_bindings_from_file(binding_path);

I can see all functions available on the string object path , but If I create the InputBundle object from amethest, I cannot see any of the functions available to execute off of that object.

Is this too be expected? Is there any way to get intellisense to work with external dependencies?

**Comment by haggerty-william** [comment] 2018-07-27 13:13
I should point out that I am on ubuntu 16.04 LTS and I am using Version: 1.25.1 of vscode and 0.4.9 of Rust(rls) using rls nightly instead of racer.

**Comment by nrc** [comment] 2018-07-29 21:13
aiui this should work as long as the source for the dependent crates which Cargo downloads is in the usual place.

cc @kngwyu - would you expect this to work? If so, any idea what is going wrong?

**Comment by kngwyu** [comment] 2018-07-30 02:08
It's intended to work, but now I don't have enough time to debug...

**Comment by kngwyu** [comment] 2018-07-31 07:28
![image](https://user-images.githubusercontent.com/16046705/43444464-bc8e8e0a-94de-11e8-837a-7f1f7aa871dd.png)
Can't reproduce with racer 2.1.3

**Comment by kngwyu** [comment] 2018-07-31 12:45
@haggerty-william
How about updating rls?

**Comment by haggerty-william** [comment] 2018-07-31 13:39
rustup and the vscode 'Update rls' command say it is up to date.

**Comment by nrc** [comment] 2018-07-31 20:35
we'll need to update the RLS in the Rust repo before rustup can update. That should happen around the end of the week. In the mean time you could build from source if you want to try it out.

**Comment by haggerty-william** [comment] 2018-08-03 12:29
updated to:
rls-preview 0.128.0-stable (7d0bc55 2018-06-07)
cargo 1.28.0 (96a2c7d16 2018-07-13)
racer 2.1.3
rustc 1.28.0 (9634041f0 2018-07-30)

VSCode:
1.25.1
1dfc5e557209371715f655691b1235b6b26a06be
x64

No change in behavior.

**Comment by cynecx** [comment] 2018-08-03 12:38
Using an updated toolchain won‘t hell right now because it still includes an old version of rls as dou can clearly see.

Clonse this repository and build it from source (nrc has mentioned this before), then configure vscode to use the freshly built rls executable.

**Comment by haggerty-william** [comment] 2018-08-03 15:30
I cannot clearly see that. What I see was an update from rls-preview 0.127.0 to rls-preview 0.128.0. Is rls-preview 0.128.0 an old version of rls even though it was published within 24 hours or so?

**Comment by cynecx** [comment] 2018-08-03 21:05
rls-preview 0.128.0-stable (**7d0bc55** **2018-06-07**)

https://github.com/rust-lang-nursery/rls/commit/7d0bc55

An updated toolchain (`rustup update`) does not exactly imply that all components has been updated.

**Comment by kngwyu** [comment] 2018-08-04 01:40
To get the latest rls you have to type
```
rustup toolchain add nightly
rustup component add --toolchain nightly rls-preview
```

I released racer 2.1.0 just 2 weeks ago maybe you need newer version not to see this bug, sorry.

**Comment by haggerty-william** [comment] 2018-08-07 12:27
Tried this on 16.04, then did a new install on 18.04 ubuntu, no use. I'm going to put learning rust aside for now, I am not used to programming without these features and it doesn't seem like anything i can do will make it work. Thanks for your help.

**Comment by DanielJoyce** [comment] 2018-08-07 19:34
@haggerty-william  You might try rls on atom. It doesn't seem to break as often. Rls support in vscode seems to break all the time and is unstable. I will have a working install for a month, run an update, and some features will break, only to start working in another update.

There really needs to be a way to test this stuff before release. It really does provide a bad experience for getting into rust.

**Comment by haggerty-william** [comment] 2018-08-08 13:46
@DanielJoyce I tried it with IntelliJ IDEA shortly after saying I was done and it didn't work there either, maybe it would work with atom but I don't really care anymore. I'll probably come back in a while and try to get things to work.

**Comment by jonathansty** [comment] 2018-09-08 15:07
I find RLS in vscode completely unusable usually. I'm using the nightly: 
```
nightly-x86_64-unknown-linux-gnu (default)
rustc 1.30.0-nightly (fc81e3624 2018-09-07)
``` 

When for example using the `glfw` crate intelisense seems to work for types I have explicetely declared but not when I do things like: 
```  
let (mut window, event_receiver) = glfw.create_window(512, 512, "framework", glfw::WindowMode::Windowed).expect("Failed to create a window!");
```

When I then try to use "window" it won't show me anything useful I could use. I then try to navigate to the symbols for that crate and that's also not really possible looking for "create_window" as a symbol yields no results...

**Comment by Elementals** [comment] 2018-10-09 14:03
To all the developers of this extension: have you evaluated the influence of the difference between "LF/CRLF" line endings?

@kngwyu  The bug may in the usage of Racer by RLS. I use "Rusty Code" extension (using just Racer) which was abandoned two years ago and everything runs flawlessly with "LF" ending (have wrong in CRLF), so at least the problem is not in the Racer.

**Comment by Elementals** [comment] 2018-10-09 14:35
To all the developers of this extension: have you evaluated the influence of the difference between "LF/CRLF" line endings? Using "LF" ending with nightly rust, everything runs flawlessly, otherwise not.

Also, Racer require nightly rust, why you haven't mention this in the VSCode page? (And this causes huge difference indeed, never get code completion work in stable rust.)

**Comment by DanielJoyce** [comment] 2018-10-09 14:41
@Elementals Will try this out later. The whole RLS situation seems a bit more stable under atom. This whole experience has kinda soured me. Great language but tooling is still borked several years on. And 2017 was supposed to be the year of productivity..

**Comment by tripokey** [comment] 2018-10-20 09:47
@Elementals Thanks a lot, just switching from CRLF to LF in vscode helped for me.

**Comment by Xanewok** [comment] 2019-04-07 18:39
This should work now and the fix for LF/CRLF has been merged in Racer some time ago. Closing this now but please reopen if the issue still persists!

**Closed by Xanewok** 2019-04-07 18:39 UTC
