### ISSUE TITLE
RLS server crashes more than 5 times

### ISSUE THREAD

**Issue by hpesoj** [rust-lang/rls-vscode#258] opened 2018-02-15 23:48 UTC
The attached test project causes the RLS server to crash more than 5 times. I have reduced the code to the minimum required to reproduce the crash. Removing any of the elements of the code seems to fix the problem.

Windows 10 Home (64-bit)
Visual Studio Code 1.20.1
Rust (rls) 0.3.2
rls-preview 0.125.0-nightly (dee42bd 2018-02-04)

[rls-crash.zip](https://github.com/rust-lang-nursery/rls-vscode/files/1729779/rls-crash.zip)

**Comment by bemeurer** [comment] 2018-03-06 18:39
I'm having similar issues with constant crashes that make it unusable

**Comment by jnicholls** [comment] 2018-04-09 21:15
Yeah I have a stupid simple project that has nothing in it, really, just importing serde and rocket.

**Comment by jnicholls** [comment] 2018-04-09 21:16
But rls is constantly crashing.

**Comment by OnlyLys** [comment] 2018-04-12 12:40
@jnicholls, if I had to guess this is due to the recent issues RLS has been having. You can follow them here https://github.com/rust-lang-nursery/rls/issues/773

**Comment by Xanewok** [comment] 2019-04-07 16:17
Can't reproduce it. In general the VSCode extension surfaces a lot more errors as to why RLS could not be started and RLS crashes less often now. I'll close this issue, please reopen if that's still happening and tell in which scenario that occurs!

**Closed by Xanewok** 2019-04-07 16:17 UTC
Labels: bug
