### ISSUE TITLE
Selecting a word does not use semantic info for higlighting

### ISSUE THREAD

**Issue by nrc** [rust-lang/rls-vscode#2] opened 2016-09-29 18:58 UTC
Putting the cursor in a word does, but actually selecting the word does not

**Comment by 0x7CFE** [comment] 2017-02-20 05:25
Isn't it intended behaviour? AFAIK KDevelop does exactly this: when you select something, it highlights all occurrences of that particular character sequence, whether putting cursor over syntax element highlights only semantics.

**Comment by jonathandturner** [comment] 2017-02-21 02:12
This uses the default behaviour for VSCode.  I'd rather we just use what they recommend rather than rolling our own.

**Comment by Xanewok** [comment] 2019-03-17 19:18
Triage: Gonna close this as 'working as intended'.

**Closed by Xanewok** 2019-03-17 19:18 UTC
