### ISSUE TITLE
rls-vscode tries to write /rls/.rustc_info.json and fails at startup: Cargo failed: Error compiling dependent crate

### ISSUE THREAD

**Issue by suztomo** [rust-lang/rls-vscode#400] opened 2018-08-19 19:26 UTC
Thank you for providing great software, Rust team.

# Problem

My VS Code's RLS plugin was complaining with error "Cargo failed: Error compiling dependent crate" even for an empty project generated by ```cargo new emptyproj --bin```.

<img width="1280" alt="screen shot 2018-08-16 at 22 12 50" src="https://user-images.githubusercontent.com/28604/44312218-a27ec500-a3c2-11e8-9cba-bdb822e6bd48.png">

# Log

With ```export RUST_LOG=rls=trace,cargo=trace``` in .bash_profile, I got following log:

```
DEBUG 2018-08-19T03:04:03Z: rls::server: Language Server starting up. Version: 0.130.5-nightly (9e4d8d5 2018-08-10)
TRACE 2018-08-19T03:04:03Z: rls::server::io: reading: 2114 bytes
TRACE 2018-08-19T03:04:03Z: rls::server: Read message `{"jsonrpc":"2.0","id":0,"method":"initialize","params":{"processId":4392,"rootPath":"/Users/suztomo/Documents/emptyproj","rootUri":"file:///Users/suztomo/Documents/emptyproj","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true},"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"executeCommand":{"dynamicRegistration":true},"configuration":true,"workspaceFolders":true},"textDocument":{"publishDiagnostics":{"relatedInformation":true},"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"contextSupport":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"]},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"hover":{"dynamicRegistration":true,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"]}},"definition":{"dynamicRegistration":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"codeAction":{"dynamicRegistration":true},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true},"documentLink":{"dynamicRegistration":true},"typeDefinition":{"dynamicRegistration":true},"implementation":{"dynamicRegistration":true},"colorProvider":{"dynamicRegistration":true}}},"initializationOptions":{"omitInitBuild":true},"trace":"off","workspaceFolders":[{"uri":"file:///Users/suztomo/Documents/emptyproj","name":"emptyproj"}]}}`
TRACE 2018-08-19T03:04:03Z: rls::server: Parsed message `RawMessage { method: "initialize", id: Num(0), params: Object({"capabilities": Object({"textDocument": Object({"codeAction": Object({"dynamicRegistration": Bool(true)}), "codeLens": Object({"dynamicRegistration": Bool(true)}), "colorProvider": Object({"dynamicRegistration": Bool(true)}), "completion": Object({"completionItem": Object({"commitCharactersSupport": Bool(true), "documentationFormat": Array([String("markdown"), String("plaintext")]), "snippetSupport": Bool(true)}), "completionItemKind": Object({"valueSet": Array([Number(1), Number(2), Number(3), Number(4), Number(5), Number(6), Number(7), Number(8), Number(9), Number(10), Number(11), Number(12), Number(13), Number(14), Number(15), Number(16), Number(17), Number(18), Number(19), Number(20), Number(21), Number(22), Number(23), Number(24), Number(25)])}), "contextSupport": Bool(true), "dynamicRegistration": Bool(true)}), "definition": Object({"dynamicRegistration": Bool(true)}), "documentHighlight": Object({"dynamicRegistration": Bool(true)}), "documentLink": Object({"dynamicRegistration": Bool(true)}), "documentSymbol": Object({"dynamicRegistration": Bool(true), "symbolKind": Object({"valueSet": Array([Number(1), Number(2), Number(3), Number(4), Number(5), Number(6), Number(7), Number(8), Number(9), Number(10), Number(11), Number(12), Number(13), Number(14), Number(15), Number(16), Number(17), Number(18), Number(19), Number(20), Number(21), Number(22), Number(23), Number(24), Number(25), Number(26)])})}), "formatting": Object({"dynamicRegistration": Bool(true)}), "hover": Object({"contentFormat": Array([String("markdown"), String("plaintext")]), "dynamicRegistration": Bool(true)}), "implementation": Object({"dynamicRegistration": Bool(true)}), "onTypeFormatting": Object({"dynamicRegistration": Bool(true)}), "publishDiagnostics": Object({"relatedInformation": Bool(true)}), "rangeFormatting": Object({"dynamicRegistration": Bool(true)}), "references": Object({"dynamicRegistration": Bool(true)}), "rename": Object({"dynamicRegistration": Bool(true)}), "signatureHelp": Object({"dynamicRegistration": Bool(true), "signatureInformation": Object({"documentationFormat": Array([String("markdown"), String("plaintext")])})}), "synchronization": Object({"didSave": Bool(true), "dynamicRegistration": Bool(true), "willSave": Bool(true), "willSaveWaitUntil": Bool(true)}), "typeDefinition": Object({"dynamicRegistration": Bool(true)})}), "workspace": Object({"applyEdit": Bool(true), "configuration": Bool(true), "didChangeConfiguration": Object({"dynamicRegistration": Bool(true)}), "didChangeWatchedFiles": Object({"dynamicRegistration": Bool(true)}), "executeCommand": Object({"dynamicRegistration": Bool(true)}), "symbol": Object({"dynamicRegistration": Bool(true), "symbolKind": Object({"valueSet": Array([Number(1), Number(2), Number(3), Number(4), Number(5), Number(6), Number(7), Number(8), Number(9), Number(10), Number(11), Number(12), Number(13), Number(14), Number(15), Number(16), Number(17), Number(18), Number(19), Number(20), Number(21), Number(22), Number(23), Number(24), Number(25), Number(26)])})}), "workspaceEdit": Object({"documentChanges": Bool(true)}), "workspaceFolders": Bool(true)})}), "initializationOptions": Object({"omitInitBuild": Bool(true)}), "processId": Number(4392), "rootPath": String("/Users/suztomo/Documents/emptyproj"), "rootUri": String("file:///Users/suztomo/Documents/emptyproj"), "trace": String("off"), "workspaceFolders": Array([Object({"name": String("emptyproj"), "uri": String("file:///Users/suztomo/Documents/emptyproj")})])}) }`
TRACE 2018-08-19T03:04:03Z: rls::server: Handling `initialize`
TRACE 2018-08-19T03:04:03Z: rls::server: init: InitializationOptions { omit_init_build: true, cmd_run: false }
TRACE 2018-08-19T03:04:03Z: rls::server::io: response: "Content-Length: 605\r\n\r\n{\"jsonrpc\":\"2.0\",\"id\":0,\"result\":{\"capabilities\":{\"textDocumentSync\":2,\"hoverProvider\":true,\"completionProvider\":{\"resolveProvider\":true,\"triggerCharacters\":[\".\",\":\"]},\"definitionProvider\":true,\"implementationProvider\":true,\"referencesProvider\":true,\"documentHighlightProvider\":true,\"documentSymbolProvider\":true,\"workspaceSymbolProvider\":true,\"codeActionProvider\":true,\"codeLensProvider\":{\"resolveProvider\":false},\"documentFormattingProvider\":true,\"documentRangeFormattingProvider\":false,\"renameProvider\":true,\"executeCommandProvider\":{\"commands\":[\"rls.applySuggestion-4403\",\"rls.deglobImports-4403\"]}}}}"
TRACE 2018-08-19T03:04:03Z: rls::config: root manifest_path: "/Users/suztomo/Documents/emptyproj/Cargo.toml"
TRACE 2018-08-19T03:04:03Z: cargo::util::toml: read_manifest; path=/Users/suztomo/Documents/emptyproj/Cargo.toml; source-id=file:///Users/suztomo/Documents/emptyproj
DEBUG 2018-08-19T03:04:03Z: cargo::core::workspace: find_root - trying /Users/suztomo/Documents/Cargo.toml
DEBUG 2018-08-19T03:04:03Z: cargo::core::workspace: find_root - trying /Users/suztomo/Cargo.toml
DEBUG 2018-08-19T03:04:03Z: cargo::core::workspace: find_root - trying /Users/Cargo.toml
DEBUG 2018-08-19T03:04:03Z: cargo::core::workspace: find_root - trying /Cargo.toml
DEBUG 2018-08-19T03:04:03Z: cargo::core::workspace: find_members - only me as a member
TRACE 2018-08-19T03:04:03Z: rls::config: For project path "/Users/suztomo/Documents/emptyproj" Cargo told us to use this target/ dir: "/Users/suztomo/Documents/emptyproj/target/rls"
TRACE 2018-08-19T03:04:03Z: rls::server::io: reading: 52 bytes
TRACE 2018-08-19T03:04:03Z: rls::server: Read message `{"jsonrpc":"2.0","method":"initialized","params":{}}`
TRACE 2018-08-19T03:04:03Z: rls::server: Parsed message `RawMessage { method: "initialized", id: Null, params: Object({}) }`
TRACE 2018-08-19T03:04:03Z: rls::server: Handling `initialized`
TRACE 2018-08-19T03:04:03Z: rls::server::io: response: "Content-Length: 382\r\n\r\n{\"jsonrpc\":\"2.0\",\"method\":\"client/registerCapability\",\"id\":1,\"params\":{\"registrations\":[{\"id\":\"rls-watch\",\"method\":\"workspace/didChangeWatchedFiles\",\"registerOptions\":{\"watchers\":[{\"globPattern\":\"/Users/suztomo/Documents/emptyproj/Cargo.lock\"},{\"globPattern\":\"/Users/suztomo/Documents/emptyproj/target\",\"kind\":4},{\"globPattern\":\"/Users/suztomo/Documents/emptyproj/Cargo.toml\"}]}}]}}"
TRACE 2018-08-19T03:04:03Z: rls::server::io: reading: 744 bytes
TRACE 2018-08-19T03:04:03Z: rls::server: Read message `{"jsonrpc":"2.0","method":"workspace/didChangeConfiguration","params":{"settings":{"rust":{"sysroot":null,"target":null,"rustflags":null,"clear_env_rust_log":true,"build_lib":null,"build_bin":null,"cfg_test":false,"unstable_features":false,"wait_to_build":1500,"show_warnings":true,"goto_def_racer_fallback":false,"use_crate_blacklist":true,"build_on_save":false,"features":[],"all_features":false,"no_default_features":false,"racer_completion":true,"jobs":null,"all_targets":true,"target_dir":"rls","racerPath":null,"rustfmtPath":null,"rustsymPath":null,"rustLangSrcPath":null,"cargoPath":null,"cargoHomePath":null,"cargoEnv":null,"formatOnSave":false,"checkOnSave":false,"checkWith":"check","useJsonErrors":false,"useNewErrorFormat":false}}}}`
TRACE 2018-08-19T03:04:03Z: rls::server: Parsed message `RawMessage { method: "workspace/didChangeConfiguration", id: Null, params: Object({"settings": Object({"rust": Object({"all_features": Bool(false), "all_targets": Bool(true), "build_bin": Null, "build_lib": Null, "build_on_save": Bool(false), "cargoEnv": Null, "cargoHomePath": Null, "cargoPath": Null, "cfg_test": Bool(false), "checkOnSave": Bool(false), "checkWith": String("check"), "clear_env_rust_log": Bool(true), "features": Array([]), "formatOnSave": Bool(false), "goto_def_racer_fallback": Bool(false), "jobs": Null, "no_default_features": Bool(false), "racerPath": Null, "racer_completion": Bool(true), "rustLangSrcPath": Null, "rustflags": Null, "rustfmtPath": Null, "rustsymPath": Null, "show_warnings": Bool(true), "sysroot": Null, "target": Null, "target_dir": String("rls"), "unstable_features": Bool(false), "useJsonErrors": Bool(false), "useNewErrorFormat": Bool(false), "use_crate_blacklist": Bool(true), "wait_to_build": Number(1500)})})}) }`
TRACE 2018-08-19T03:04:03Z: rls::server: Handling `workspace/didChangeConfiguration`
TRACE 2018-08-19T03:04:03Z: rls::actions::notifications: config change: Object({"rust": Object({"all_features": Bool(false), "all_targets": Bool(true), "build_bin": Null, "build_lib": Null, "build_on_save": Bool(false), "cargoEnv": Null, "cargoHomePath": Null, "cargoPath": Null, "cfg_test": Bool(false), "checkOnSave": Bool(false), "checkWith": String("check"), "clear_env_rust_log": Bool(true), "features": Array([]), "formatOnSave": Bool(false), "goto_def_racer_fallback": Bool(false), "jobs": Null, "no_default_features": Bool(false), "racerPath": Null, "racer_completion": Bool(true), "rustLangSrcPath": Null, "rustflags": Null, "rustfmtPath": Null, "rustsymPath": Null, "show_warnings": Bool(true), "sysroot": Null, "target": Null, "target_dir": String("rls"), "unstable_features": Bool(false), "useJsonErrors": Bool(false), "useNewErrorFormat": Bool(false), "use_crate_blacklist": Bool(true), "wait_to_build": Number(1500)})})
TRACE 2018-08-19T03:04:03Z: rls::actions::notifications: Updated config: Config { sysroot: None, target: None, rustflags: None, build_lib: Inferred(false), build_bin: Inferred(None), cfg_test: false, unstable_features: false, wait_to_build: 1500, show_warnings: true, goto_def_racer_fallback: false, clear_env_rust_log: true, build_on_save: false, use_crate_blacklist: true, target_dir: Specified(Some("rls")), features: [], all_features: false, no_default_features: false, jobs: None, all_targets: true, racer_completion: true, clippy_preference: OptIn, full_docs: Inferred(false), show_hover_context: true }
TRACE 2018-08-19T03:04:03Z: rls::build: request_build Cargo
TRACE 2018-08-19T03:04:03Z: rls::server::io: response: "Content-Length: 165\r\n\r\n{\"jsonrpc\":\"2.0\",\"method\":\"client/unregisterCapability\",\"id\":2,\"params\":{\"unregisterations\":[{\"id\":\"rls-range-formatting\",\"method\":\"textDocument/rangeFormatting\"}]}}"
TRACE 2018-08-19T03:04:03Z: rls::build: run_build, "/Users/suztomo/Documents/emptyproj" Cargo
TRACE 2018-08-19T03:04:03Z: rls::build: running build
TRACE 2018-08-19T03:04:03Z: rls::build::plan: read metadata "/Users/suztomo/Documents/emptyproj/Cargo.toml"
TRACE 2018-08-19T03:04:03Z: rls::server::io: response: "Content-Length: 92\r\n\r\n{\"jsonrpc\":\"2.0\",\"method\":\"window/progress\",\"params\":{\"id\":\"progress_1\",\"title\":\"Building\"}}"
TRACE 2018-08-19T03:04:03Z: rls::server::io: reading: 38 bytes
TRACE 2018-08-19T03:04:03Z: rls::server: Read message `{"jsonrpc":"2.0","id":1,"result":null}`
TRACE 2018-08-19T03:04:03Z: rls::server::io: reading: 38 bytes
TRACE 2018-08-19T03:04:03Z: rls::server: Read message `{"jsonrpc":"2.0","id":2,"result":null}`
TRACE 2018-08-19T03:04:03Z: rls::build: Specified work: NeedsCargo(Default)
TRACE 2018-08-19T03:04:03Z: rls::build::cargo: root manifest_path: "/Users/suztomo/Documents/emptyproj/Cargo.toml"
TRACE 2018-08-19T03:04:03Z: cargo::util::toml: read_manifest; path=/Users/suztomo/Documents/emptyproj/Cargo.toml; source-id=file:///Users/suztomo/Documents/emptyproj
DEBUG 2018-08-19T03:04:03Z: cargo::core::workspace: find_root - trying /Users/suztomo/Documents/Cargo.toml
DEBUG 2018-08-19T03:04:03Z: cargo::core::workspace: find_root - trying /Users/suztomo/Cargo.toml
DEBUG 2018-08-19T03:04:03Z: cargo::core::workspace: find_root - trying /Users/Cargo.toml
DEBUG 2018-08-19T03:04:03Z: cargo::core::workspace: find_root - trying /Cargo.toml
DEBUG 2018-08-19T03:04:03Z: cargo::core::workspace: find_members - only me as a member
TRACE 2018-08-19T03:04:03Z: rls::build::cargo: Cargo compilation options:
CargoOptions { target: None, lib: false, bin: [], bins: false, all_features: false, no_default_features: false, features: [], jobs: None, all_targets: true }
TRACE 2018-08-19T03:04:03Z: rls::build::cargo: Specified packages to be built by Cargo: {
    "emptyproj"
}
TRACE 2018-08-19T03:04:03Z: cargo::ops::resolve: previous: graph: Graph {
  - emptyproj v0.1.0 (file:///Users/suztomo/Documents/emptyproj)
}

features: {
}
TRACE 2018-08-19T03:04:03Z: cargo::core::registry: register_lock: emptyproj v0.1.0 (file:///Users/suztomo/Documents/emptyproj)
DEBUG 2018-08-19T03:04:03Z: cargo::ops::resolve: attempting to prefer emptyproj v0.1.0 (file:///Users/suztomo/Documents/emptyproj)
DEBUG 2018-08-19T03:04:03Z: cargo::core::registry: load/missing  file:///Users/suztomo/Documents/emptyproj
DEBUG 2018-08-19T03:04:03Z: cargo::core::registry: loading source file:///Users/suztomo/Documents/emptyproj
DEBUG 2018-08-19T03:04:03Z: cargo::sources::config: loading: file:///Users/suztomo/Documents/emptyproj
TRACE 2018-08-19T03:04:03Z: cargo::core::source::source_id: loading SourceId; file:///Users/suztomo/Documents/emptyproj
TRACE 2018-08-19T03:04:03Z: cargo::ops::cargo_read_manifest: read_package; path=/Users/suztomo/Documents/emptyproj/Cargo.toml; source-id=file:///Users/suztomo/Documents/emptyproj
TRACE 2018-08-19T03:04:03Z: cargo::util::toml: read_manifest; path=/Users/suztomo/Documents/emptyproj/Cargo.toml; source-id=file:///Users/suztomo/Documents/emptyproj
TRACE 2018-08-19T03:04:03Z: cargo::core::registry: locking summary of emptyproj v0.1.0 (file:///Users/suztomo/Documents/emptyproj)
DEBUG 2018-08-19T03:04:03Z: cargo::core::resolver: initial activation: emptyproj v0.1.0 (file:///Users/suztomo/Documents/emptyproj)
TRACE 2018-08-19T03:04:03Z: cargo::core::resolver: activating emptyproj v0.1.0 (file:///Users/suztomo/Documents/emptyproj)
TRACE 2018-08-19T03:04:03Z: cargo::core::resolver: resolved: graph: Graph {
  - emptyproj v0.1.0 (file:///Users/suztomo/Documents/emptyproj)
}

features: {
}
TRACE 2018-08-19T03:04:03Z: cargo::ops::resolve: previous: graph: Graph {
  - emptyproj v0.1.0 (file:///Users/suztomo/Documents/emptyproj)
}

features: {
}
TRACE 2018-08-19T03:04:03Z: cargo::core::registry: register_lock: emptyproj v0.1.0 (file:///Users/suztomo/Documents/emptyproj)
DEBUG 2018-08-19T03:04:03Z: cargo::ops::resolve: attempting to prefer emptyproj v0.1.0 (file:///Users/suztomo/Documents/emptyproj)
DEBUG 2018-08-19T03:04:03Z: cargo::core::registry: load/locked   file:///Users/suztomo/Documents/emptyproj
TRACE 2018-08-19T03:04:03Z: cargo::core::registry: locking summary of emptyproj v0.1.0 (file:///Users/suztomo/Documents/emptyproj)
DEBUG 2018-08-19T03:04:03Z: cargo::core::resolver: initial activation: emptyproj v0.1.0 (file:///Users/suztomo/Documents/emptyproj)
TRACE 2018-08-19T03:04:03Z: cargo::core::resolver: activating emptyproj v0.1.0 (file:///Users/suztomo/Documents/emptyproj)
TRACE 2018-08-19T03:04:03Z: cargo::core::resolver: resolved: graph: Graph {
  - emptyproj v0.1.0 (file:///Users/suztomo/Documents/emptyproj)
}

features: {
}
TRACE 2018-08-19T03:04:03Z: cargo::core::registry: getting packages; sources=1
TRACE 2018-08-19T03:04:03Z: cargo::sources::path: getting packages; id=emptyproj v0.1.0 (file:///Users/suztomo/Documents/emptyproj)
DEBUG 2018-08-19T03:04:03Z: cargo::util::rustc: adding rustup info to rustc fingerprint
TRACE 2018-08-19T03:04:03Z: cargo::util::errors: error: No such file or directory (os error 2)
TRACE 2018-08-19T03:04:03Z: cargo::util::errors: 	context: failed to read `/rls/.rustc_info.json`
 INFO 2018-08-19T03:04:03Z: cargo::util::rustc: failed to read rustc info cache: failed to read `/rls/.rustc_info.json`
 INFO 2018-08-19T03:04:03Z: cargo::util::rustc: rustc info cache miss
DEBUG 2018-08-19T03:04:03Z: cargo::core::compiler::build_context: probe_target_info
 INFO 2018-08-19T03:04:03Z: cargo::util::rustc: rustc info cache miss
 INFO 2018-08-19T03:04:03Z: cargo::util::rustc: rustc info cache miss
TRACE 2018-08-19T03:04:03Z: cargo::util::errors: error: Permission denied (os error 13)
TRACE 2018-08-19T03:04:03Z: cargo::util::errors: 	context: failed to open: /rls/debug/.cargo-lock
TRACE 2018-08-19T03:04:03Z: cargo::util::errors: error: No such file or directory (os error 2)
TRACE 2018-08-19T03:04:03Z: cargo::util::errors: 	context: failed to write `/rls/.rustc_info.json`
 WARN 2018-08-19T03:04:03Z: cargo::util::rustc: failed to update rustc info cache: failed to write `/rls/.rustc_info.json`
DEBUG 2018-08-19T03:04:03Z: rls::build::cargo: Error running compile_with_exec: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }

failed to open: /rls/debug/.cargo-lock
TRACE 2018-08-19T03:04:03Z: rls::server::io: response: "Content-Length: 104\r\n\r\n{\"jsonrpc\":\"2.0\",\"method\":\"window/progress\",\"params\":{\"done\":true,\"id\":\"progress_1\",\"title\":\"Building\"}}"
DEBUG 2018-08-19T03:04:03Z: rls::build::cargo: Cargo failed: Error compiling dependent crate
TRACE 2018-08-19T03:04:03Z: rls::actions::post_build: build - Error Cargo failed: Error compiling dependent crate when running None
TRACE 2018-08-19T03:04:03Z: rls::server::io: response: "Content-Length: 92\r\n\r\n{\"jsonrpc\":\"2.0\",\"method\":\"window/progress\",\"params\":{\"id\":\"progress_0\",\"title\":\"Indexing\"}}"
TRACE 2018-08-19T03:04:03Z: rls::server::io: response: "Content-Length: 125\r\n\r\n{\"jsonrpc\":\"2.0\",\"method\":\"window/showMessage\",\"params\":{\"message\":\"Cargo failed: Error compiling dependent crate\",\"type\":1}}"
TRACE 2018-08-19T03:04:03Z: rls::server::io: response: "Content-Length: 104\r\n\r\n{\"jsonrpc\":\"2.0\",\"method\":\"window/progress\",\"params\":{\"done\":true,\"id\":\"progress_0\",\"title\":\"Indexing\"}}"

```

The solution I found was to set "rust.target_dir" to either null or somewhere writable by the current user.

# My environment
Mac OS 10.13.6 (17G65)
VS Code 1.21.1 (1.21.1)
rls-preview 0.130.5-nightly (9e4d8d5 2018-08-10)
RLS runs with / as working directory
```
~ $ lsof -d cwd  |grep rls
..
rls       441 suztomo  cwd    DIR    1,4      928          2 /
```

# Analysis
My interpretation of [rls's cargo.rs L594](https://github.com/rust-lang-nursery/rls/blob/08be5190d52cdc6706cf2aaf82729a3485d4d9f8/src/build/cargo.rs#L594):

> If there's any value specified for target_dir, then RLS recognizes it as an absolute path (path from RLS's working directory "/").
> Otherwise, it uses target/rls in build directory.

However, rls-vscode specifies "rls" as default value of ```rust.target_dir```, resulting in the problem of accessing "/rls" in absolute path.

I appreciate if somebody can confirm/fix this problem.

**Comment by Kane-Sendgrid** [comment] 2018-08-24 22:36
@suztomo I'm having same problem, how did you get log (where can you see it?). Thanks!

**Comment by suztomo** [comment] 2018-08-25 01:37
@Kane-Sendgrid  Here you are:
<img width="1280" alt="how_to_read_rls_log" src="https://user-images.githubusercontent.com/28604/44613709-d2283580-a7e5-11e8-9e79-20a1d8d21b67.png">

**Comment by Kane-Sendgrid** [comment] 2018-08-25 01:49
@suztomo Thanks for detailed instructions! Looks like my issue was a bit different - in nightly mode rls doesn't event start without any logs: #409 

This is very helpful though, I can see how it fails in stable channel (as I'm using nightly features).

**Comment by jamesray1** [comment] 2018-09-24 23:43
I can't reproduce this:
```bash
➜  Rust cargo new emptyproj --bin
     Created binary (application) `emptyproj` project
➜  Rust cd emptyproj
➜  emptyproj git:(master) ✗ cargo build
   Compiling emptyproj v0.1.0 (file:///home/james/Rust/emptyproj)
    Finished dev [unoptimized + debuginfo] target(s) in 14.85s
```

**Comment by suztomo** [comment] 2018-09-25 02:55
@jamesray1 Are you facing problem to reproduce the following error in rls-vscode?

    Cargo failed: Error compiling dependent crate

From the output you added, I see your "emptyproj" works fine without using VS Code.

**Comment by jamesray1** [comment] 2018-09-25 06:36
Sorry I forgot to mention the above was done in VS Code.

**Comment by suztomo** [comment] 2018-09-25 17:58
I created the emptyproj in command line, and opened the emptyproj directory in VSCode. Then I got the error in the screenshot of the description.

I’m happy to upload a video if it’s not reproducible.

**Comment by jamesray1** [comment] 2018-09-26 23:53
OK, this is just in the terminal:
```bash
➜  rust cargo new emptyproj --bin
     Created binary (application) `emptyproj` project
➜  rust cd emptyproj
➜  emptyproj git:(master) ✗ cargo build
   Compiling emptyproj v0.1.0 (file:///home/james/rust/emptyproj)
    Finished dev [unoptimized + debuginfo] target(s) in 8.18s
```

And this is in VS code after `cargo new emptyproj --bin` in GNOME terminal:
```
➜  emptyproj git:(master) ✗ cargo build
   Compiling emptyproj v0.1.0 (file:///home/james/rust/emptyproj)
    Finished dev [unoptimized + debuginfo] target(s) in 8.22s
```
So it seems like your issue is caused by something local to your system.

PS, I'm not a developer of this extension, I'll leave further troubleshooting between you and them.

**Comment by suztomo** [comment] 2018-09-27 00:01
@jamesray1 Interesting. Are you able to reproduce the issue in the video, or not?
(You don't run anything in VS Code; Just open the folder.)

**Comment by jamesray1** [comment] 2018-09-27 01:09
In GNOME terminal:
```
➜  rust cargo new emptyproj --bin
     Created binary (application) `emptyproj` project
➜  rust cd emptyproj
➜  emptyproj git:(master) ✗ cargo build
   Compiling emptyproj v0.1.0 (file:///home/james/rust/emptyproj)
    Finished dev [unoptimized + debuginfo] target(s) in 8.18s
```
Opening the folder in VS Code is then successful.

**Comment by Xanewok** [comment] 2019-04-07 18:16
`target_dir` default setting was fixed a while back and I can't reproduce the issue as well, I'm sorry. I'm closing the issue due to issue triage but please reopen this if you're still encountering this!

**Closed by Xanewok** 2019-04-07 18:16 UTC
Labels: P-High, bug
