### ISSUE TITLE
VS tasks not present on install version 0.6.0

### ISSUE THREAD

**Issue by JamieDStewart** [rust-lang/rls-vscode#557] opened 2019-04-01 22:21 UTC
Downloaded fresh install of VS plugin on new machine. Followed instructions as per readme, no tasks present after install to build, run etc once install complete.
Press ctrl+shift+b no build task option.
Press ctrl+shift+p search for rust tasks, no “rust: cargo ...” tasks appear in task lists.
Reverting VS plugin to previous version and all rust cargo tasks appear as expected, ctrl+shift+b build task present on previous version not in latest.

**Comment by Tape** [comment] 2019-04-02 01:56
I'm seeing the same, it's also giving me errors indicating rustup is not installed. Reverting to the previous version fixed the issue (Running on Linux).

**Comment by mattrudder** [comment] 2019-04-02 02:25
Same here. Upgraded my install from 0.5.4 and was unable to use previously defined build tasks.

Windows 10 Build 1809
VSCode v1.32.3

**Comment by pycebs** [comment] 2019-04-02 11:17
I have the same problem. I cannot use the cargo run/build/etc tasks anymore. They just disappeared.

My info:

Version: 1.32.3
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-21T22:49:07.188Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 5.0.5-arch1-1-ARCH

**Comment by dvic** [comment] 2019-04-02 15:11
Same here.

**Comment by Xanewok** [comment] 2019-04-02 16:25
Sorry for the breakage - I tried to test every change during work towards 0.6 but this must’ve slipped through during a refactor. I’m on it and will release 0.6.1 with the fix; hopefully this isn’t too disruptive for your workflow! For now you can work around this and specify your own build/test watch tasks using tasks.json definitions

**Comment by skrap** [comment] 2019-04-03 03:26
temporary workaround: context-click on the RLS extension in the extensions list, and select "Install Another Version..." to downgrade to 0.5.4.
<img width="417" alt="image" src="https://user-images.githubusercontent.com/1132698/55450872-a7ce0000-559e-11e9-9e40-faa4281e1880.png">

**Comment by Xanewok** [comment] 2019-04-04 10:30
Version 0.6.1 has been released with the fix - please let me know if the issue is fixed for you.

**Comment by pycebs** [comment] 2019-04-04 11:20
Some options are back: cargo build, check, clean and test.

But cargo run is still missing. Any idea why?

**Comment by Xanewok** [comment] 2019-04-04 16:29
That may be unpopular but I decided to leave out the run task to align more with what VSCode uses tasks for (build/rebuild/clean/test); the launch configuration is separated and handled differently. I'd love to investigate how we can hook up debugging to provide more first-class VSCode launch environment but decided to leave it out for now so that future transition to F5-style run/debug is more obvious.

Since the tasks are now back and working, I'll close the issue. Sorry for the inconvenience once more!

**Closed by Xanewok** 2019-04-04 16:29 UTC

**Comment by skrap** [comment] 2019-04-04 16:56
@Xanewok Thanks for the quick turnaround! So, to summarize, your intended replacement for `cargo run` is to create a launch.json entry for the cargo invocation in question, and then do "Start Debugging" or "Start Without Debugging" as desired?

**Comment by Xanewok** [comment] 2019-04-04 17:06
Yep, that's the plan! https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb is a good extension and provides good out-of-box experience for Cargo projects so most likely this will either end up as an extension dependency (such that it's also installed alongside the current extension) or we'll strongly suggest to also install it manually if the user decides that they also want to interactively debug their code.

**Comment by jasonwilliams** [comment] 2019-04-04 18:01
@Xanewok  what do i do if i just simply want to cargo run within vscode in the meantime?

**Comment by pycebs** [comment] 2019-04-04 21:57
@Xanewok Oh no. I loved that cargo run functionality. I don't want to setup 1000 different things. Install my Rust plugin in VSCode and simply start using it. Is this you absolute final decision? I think extensions like this are supposed to make life easier for developers.

**Comment by Xanewok** [comment] 2019-04-05 10:31
There are never absolute final decisions =) I understand that and it seems fair; I agree that the decision was hasty and it'd be better to just give the user more choices to pick from rather than try to lock them in the explicit VSCode design.

I'll add back the `cargo run` task in the next point release.

However, I won't add back the `cargo +nightly bench` command since:
1) it's nightly-only and limited to a specific rustc-internal bencher (there's seems to be a community consensus to move towards the great [criterion](https://crates.io/crates/criterion) package)
2) there's currently an [ongoing effort](https://github.com/rust-lang/libtest/pull/11) to make libtest (rustc-internal test and benchmarking harness) work on stable and move it out of Rust tree

Because of that, we'll add the bench command when the benchmarking story will be resolved and it will be usable on stable.

**Comment by skrap** [comment] 2019-04-05 15:22
@Xanewok This fix doesn't work for me.  Could it be because I'm using a cargo workspace?  I still have no tasks, even with 0.6.1.  0.5.4 works correctly.
If I open the directory containing the individual crate, building works, but all of the paths in the cargo output are cargo-workspace-relative, so none of the navigation features work properly.
If you'd rather I file a separate issue for this case, I'm happy to.

**Comment by Xanewok** [comment] 2019-04-07 20:23
Cargo workspace means there's a Cargo.toml at the root, correct? If so, this should work as expected; if it doesn't, please file an issue with a simple repro project.

**Comment by wrathofodin** [comment] 2019-07-22 20:55
Is there any way to make "Start Debugging" and "Start Without Debugging" work?
